### ISSUE TITLE
Too many binary files written to directory

### ISSUE THREAD

**Issue by pbitzer** [hamma-dev/mjolnir-hamma#18]
Right now, we are writing a binary HAMMA file for every trigger. This quickly leads to a situation in which we can no longer write more files because the underlying filesystem cannot handle "a lot" of files in the directory. The error appears as misleading "not enough space" error. (Took a while to track this down.) "A lot" seems to be ~16k files.

So, we need to either figure out a way to not write so many files (I don't think this is possible), or find a way to add some sub-directories to write to. Currently I'm thinking of subclassing `brokkr.outputs.binaryfile.BinaryFileOutput` to dynamically add some directories on the fly, but more ideas are welcome!

**Comment by pbitzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Develop file shepard](https://trello.com/c/OeUNCb6O/21-develop-file-shepard)

**Comment by CAM-Gerlach** [comment]
Ah, good point. It wouldn't be a an issue with any modern filesystem, at least up to the drive's capacity, but for compatibility reasons, the drives are using ye olde FAT32. It nominally can store a max of 2^16 (65k) files per directory, but that's only with files who's names follow the 8.3 convention; longer names take up additional slots per file for each chunk of name length above this. Based on your emprical testing, it seems highly likely this number is 3 extra chunks per file, since at three chunks per file the maximum is right about 16k.

I'd suggest adding one subdir per day, which matches the naming and organization elsewhere, and is enough for 4.5 hours at the max 60 triggers per minute continuous, or an average of 11 triggers per hour for the full 24 hours. At least per the past telemetry data I've seen, it _should_ sufficient for real-world use, particularly considering it would basically fill up the sensor's own internal/USB drive on its own, though for safety you could include the hour as well, which would make it impossible for it to roll over.

I am not able to confirm it at the moment since I don't have a sensor handy, but per double-checking the code, you _should_ be able to do this by just tweaking the config. Specifically, if you add the desired subdir name pattern to the `filename_template` under `steps.science_binary_output` in `main.toml` with no changes to Brokkr; it should automatically inject the date/time (or any other variables you choose) in whatever format you specify and create the directory if it doesn't exist. You should even be able to have arbitrarily nested directories, e.g. `year/month/day/hour` etc., if you want.

**Comment by pbitzer** [comment]
This is a good example where I'm still learning all the ins and outs of brokkr. I had written a plugin that inherited the binary output,  and did all kinds of hacky stuff. It worked, but it wasn't pretty. 

Initial testing looks like this works well. One question: should the path mods go under the field `filename_template` as suggested, or under `output_path`? Naively, I would think the latter.

This needs to go into production ASAP. It's already caused some issues. One of the bad knock-on issues is that if we get a "not enough space" error, the packet is lost, i.e., there is no fallback.

**Comment by CAM-Gerlach** [comment]
Really sorry, I missed this somehow yesterday despite having a priority notification filter for the project-mjolnir and hamma-dev orgs and checking manually frequently.

> Initial testing looks like this works well. One question: should the path mods go under the field filename_template as suggested, or under output_path? Naively, I would think the latter.

I naively thought the same too, but glancing at the code, but some of the error messages implied that `output_path` was checked if it existed first and raised an error if it didn't, and Brokkr would only create the portion in the `filename_template`, which I why I recommended the latter. However, looking more carefully, both parts should actually work equally well, with the same injected parameters, preprocessing and automatic creation. So yeah, to make a long story short, `output_path` would make the most conceptual sense.

> One of the bad knock-on issues is that if we get a "not enough space" error, the packet is lost, i.e., there is no fallback.

There is a bunch of configurable fallback logic around using one drive if the other is full, and if both aren't available it will temporarily fall back to the Pi's card (and as discussed in #20 , it would also be able to fall back to the sensor's own drive as a large circular buffer), but since the problem is due to invisible filesystem file count limits instead, it doesn't get triggered.

> This needs to go into production ASAP. It's already caused some issues. 

Let me know if I can help further, and once you have a PR ready and tested we can merge it posthaste (I will do my best to review it as soon as I see it, but don't feel obligated to wait for something if its particularly critical or straightforward—you're the boss here, after all :).
